project_id = "rivkrzxrsnsrubnfvdvy"

[functions.generate-threat-image]
verify_jwt = false

[functions.process-detection]
verify_jwt = false

[functions.log-blockchain]
verify_jwt = false

[functions.send-alert]
verify_jwt = false

[functions.analyze-satellite]
verify_jwt = false

[functions.sms-webhook]
verify_jwt = false

[functions.fetch-satellite-hotspots]
verify_jwt = false

[functions.send-broadcast-alert]
verify_jwt = true

[functions.sms-response]
verify_jwt = false
